services:
  api:
    build:
      context: ../../api
      dockerfile: Dockerfile
    container_name: deudamundi-api
    env_file:
      - ./.env.api
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "127.0.0.1:8000:8000"

  redis:
    image: redis:7-alpine
    container_name: deudamundi-redis
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
